BaseUrl= "https://luishmr0.github.io/b2/"
LanguageCode= "es-ES"
Title= "luishmr0"
paginate = 5
DisqusShortname = "luishmr0"
Copyright = "All rights reserved - 2016"
canonifyurls = true
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Acerca"
url = "/about"
weight = -100
[[menu.main]]
name = "Github"
pre = "<h3>Follow me</h3>"
url = "https://github.com/luishmr0"
weight = 100
[[menu.main]]
name = "Twitter"
url = "https://twitter.com/luis_hmr0"
weight = 101
[[menu.main]]
name = "Heroes of the Storm"
url = "http://www.hotslogs.com/Player/Profile?PlayerID=2484740"
weight = 102

[params]
  description = "software engineering student, football, bookworm, gamer, movies;"
  cover = "images/bg.jpg"
  author = "Luis Marin"
  authorlocation = "Peru"
  authorwebsite = "http://lhmr.tech"
  bio= "software engineering student, football, bookworm, gamer, movies;"
  logo = "images/darth.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "luishmr0"
  twitterName = "luis_hmr0"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "luis_hmro"
